Jason C. Reyes

21 December 2024

In [57]:
from postgres_connection import db
import pandas as pd

with db() as conn:
    cur = conn.execute('''
        SELECT * 
            FROM "EUGasNet"
            WHERE "import_country_code" = 'DE'
            LIMIT 10;
        ''')
    df = pd.DataFrame(cur.fetchall(), columns = [d[0] for d in cur.description]).style.hide(axis = "index")
df

In [58]:
with db() as conn:
    cur = conn.execute('''
        SELECT COUNT(*) FROM "EUGasSC";
        SELECT COUNT(*) FROM "EUGasNet";
        ''')
    
    tables = ["EUGasSC", "EUGasNet"]
    for t in tables:
        record = cur.fetchone()
        print(f"Total rows in {t}: {record[0]}")
        if t != tables[-1]:    # Skip nextset() for last table.
            cur.nextset()

Total rows in EUGasSC: 67985
Total rows in EUGasNet: 154296